name: Events
highlighter: rouge
url: "http://selectusa.github.io"
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
future: true
collections:
- events
