name: Events
highlighter: pygments
url: "http://selectusa.github.io"
baseurl: "/events"
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
collections:
- events
